### PR TITLE
Added .svg logo

### PR DESCRIPTION
**Pull request by phlaster**
Hello! This is my first ever pull request. I've been writing in Julia for a while now and always wanted to contribute anything to the community, so as I've met your little package, I thought it deserves a logo. I used authentic Julia colours to draw it in Inkscape and put it into `deps` directory, as I saw the other Julia packages store icons and pictures there.  Hope you'll find this little logo appropriate, and If so -- link it to README.md and to other places where the logo should be exposed.

### CODE REVIEW

**Comment by oscardssmith** [comment]
looks good! how are the colors chosen? I'm not sure everywhere the logo should be. probably the docs and on the GitHub repo. not sure if there's anywhere else

**Comment by phlaster** [comment]
I took the colors from [[julia-logo-graphics](https://github.com/JuliaLang/julia-logo-graphics)](https://github.com/JuliaLang/julia-logo-graphics). The shape itself is the center of the [Ulam spiral](https://en.wikipedia.org/wiki/Ulam_spiral), which was the first thing, which came to my mind. At first I tried to set the colors according some obscure pattern, but then just spread them more or less at random.

Yeah, the docs was the first link I visited. It would be nice to see the logo there.

**Comment by oscardssmith** [comment]
looks good! how are the colors chosen? I'm not sure everywhere the logo should be. probably the docs and on the GitHub repo. not sure if there's anywhere else

**Comment by oscardssmith** [comment]
sorry for not getting back earlier. I think this is good to merge. I just futzed with it a little to try and make CI happy

**Comment by phlaster** [comment]
I had some time to think about this merge request, I'd better create commit with all changes needed (Including README.md and Docs updates). Now I am refining the logo, so I'd better close this one.
screenshot

**Pull request closed without merging**
