### PR TITLE
Copied docstrings to README

### PR DESCRIPTION
**Pull request by ararslan**
Addresses #3. I'm not crazy about the formatting; I tried to mimic the look of the docs and I don't know how well it translated to markdown.

### CODE REVIEW

**Comment by ararslan** [comment]
Hm, having decreased coverage show as a failed check is a little unfortunate. @tkelman Any idea if there's a better way to set up the coverage testing? I don't think Julia has it as a check like this.

**Comment by tkelman** [comment]
This looks fine to me, thanks! This was the last thing needed before registering as far as I'm concerned.

There might be a way to configure coveralls to allow small coverage drops, otherwise I think most people just ignore it.

**Comment by ararslan** [comment]
@tkelman Available PR alert settings for Coveralls are:
* Leave comments? (checked)
* Use status API? (checked)
* Coverage threshold for failure (blank)
* Coverage decrease threshold for failure (blank)

I don't know what any of those mean. I'd personally prefer not to have decreased coverage show up as a failed check because it makes it less obvious whether Travis and AppVeyor failed.

**Comment by tkelman** [comment]
I think what you want is to disable "Use status API" then, that way it won't submit a data point for the checkbox on PR's. I personally find the PR comments annoying noise, but blocking Coveralls and Codecov's bots at least made my inbox a little quieter.

**Comment by ararslan** [comment]
I can turn those off too if you'd prefer.

**Comment by tkelman** [comment]
Some people like them, and if you'd rather not have coverage info show up in the status API then they won't otherwise be visible in PR's right away. I think setting one of the thresholds for failure (dunno what the difference is) would have coverage info available but not flag a failure?

**Comment by ararslan** [comment]
I think the first listed threshold for failure is a percent coverage below which any check would fail. The second threshold is the allowable percent decrease in coverage, so if you submit a PR that decreases coverage by x+1% and the threshold is x% then it fails. That's what I'd guess anyway.

The latter could be a good idea, it's just a matter of deciding on a meaningful threshold. For example, copying the docs in the README decreased coverage by 2% (which I honestly don't understand at all) so clearly 2% isn't a good threshold...

**Pull request merged**
