### PR TITLE
add count_primes

### PR DESCRIPTION
**Pull request by oscardssmith**
Based off of discussion in https://github.com/JuliaMath/Primes.jl/issues/99, this turns the existing prime sieve into a more efficient segmented one. This is about 5x slower than [FastPrimeSieve](https://github.com/haampie/FastPrimeSieve.jl/tree/master/src) (as tested on 10^10), but also only takes about 30 new lines of code. This will be a better foundation for https://github.com/JuliaMath/Primes.jl/pull/102

### CODE REVIEW

**Comment by haampie** [comment]
Notice that `FastPrimeSieve.pcountprimes` is threaded, which gives more speedup:

```
julia> @time Primes.count_primes(1, 10^10)
 22.230106 seconds (162.77 k allocations: 2.545 MiB)
455052511

julia> @time FastPrimeSieve.countprimes(10^10)
  2.389320 seconds (7 allocations: 277.109 KiB)
455052511

julia> @time FastPrimeSieve.pcountprimes(10^10)
  0.269437 seconds (14.94 k allocations: 4.173 MiB, 0.00% compilation time)
455052511

julia> @time FastPrimeSieve.pcountprimes(10^10, segment_length=128*1024)
  0.195094 seconds (243 allocations: 4.828 MiB)
455052511
```

So it's about a factor 114 slower on my 8 core AMD processor after a bit of tuning

**Comment by oscardssmith** [comment]
I was comparing to single threaded since I also plan to eventually add multithreading to this code. I believe the main place improvement to be made is that currently, the inner loop has a `divrem` to calculate the index that accounts for a lot of the time in the algorithm, and I think it is removable.

**Comment by haampie** [comment]
Yeah, the offset can be saved after the last iteration of each prime number inside every segment

**Comment by oscardssmith** [comment]
Closing this since https://github.com/JuliaMath/Primes.jl/pull/102 is a better path forwards.

**Pull request closed without merging**
